; This file contains Rainmeter skin translations to English.
; If you want to translate your skin to another language:
; - Copy this file and rename it to <lang_name>.inc
; - Replace all variable values below with translated ones
; - Replace 'lang' variable in Config.inc with your language name
; - Refresh all in Rainmeter.
[Variables]
    mps=m/s
    mmHg=mm Hg
    wind=Wind
    humidity=Humidity
    pressure=Pressure
    ;
    monday=Monday
    tuesday=Tuesday
    wednesday=Wednesday
    thursday=Thursday
    friday=Friday
    saturday=Saturday
    sunday=Sunday
    ;
    january=January
    february=February
    march=March
    april=April
    may=May
    june=June
    july=July
    august=August
    september=September
    october=October
    november=November
    december=December
    ;
    loading=N/A
    s_bat=Battery level
    s_average_cpu=Average Central Processing Unit usage
    s_average_ram=Average Random Access Memory usage
    s_disk_time=Disk active time
    s_cpu_max_temp=Temperature of the hottest CPU